### ISSUE TITLE
__fish_prog_needs_command won't work for wrappers

### ISSUE THREAD

**Issue by faho** [tuvistavie/fish-completion-helpers#1]
fish's completion has the notion of a wrapped completion (`complete -w`), which will break here because __fish_prog_needs_command explicitly checks argv[1]. Similarly, this will also break with `and $COMMAND` and similar. See https://github.com/fish-shell/fish-shell/commit/5e555fc1cfca001e689dc2598d0395472d8c6f4a and the related https://github.com/fish-shell/fish-shell/issues/2025.

**Comment by faho** [comment]
The solution of course is to simply remove the check.

**Comment by danhper** [comment]
Thanks, I just fixed this! :+1:
